name: Build Seed Data

on:
  # we want pull requests so we can build(test) but not push to image registry
  push:
    branches:
      - 'main'
    # only build when important files change
    paths:
      - 'seed-data/**'
      - '.github/workflows/docker-build-seed-data.yaml'
  pull_request:
    branches:
      - 'main'
    # only build when important files change
    paths:
      - 'seed-data/**'
      - '.github/workflows/docker-build-seed-data.yaml'

env:
  REGISTRY: pinoched

jobs:
  
  build-seed-data:
    runs-on: ubuntu-latest
    steps:
    
      - 
        name: Check out the repo
        uses: actions/checkout@v3
   
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: Set VERSION
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV

      - 
        name: Build and push result image
        uses: docker/build-push-action@v4
        with:
          dockerfile: seed-data/Dockerfile
          context: seed-data
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/seed-data:${{ env.GITHUB_SHA_SHORT }}
            ${{ secrets.DOCKER_USERNAME }}/seed-data:latest
        
