name: Build Result

on:
  # we want pull requests so we can build(test) but not push to image registry
  push:
    branches:
      - "main"
    # only build when important files change
    paths:
      - "result/**"
      - ".github/workflows/docker-build-result.yaml"
  pull_request:
    branches:
      - "main"
    # only build when important files change
    paths:
      - "result/**"
      - ".github/workflows/docker-build-result.yaml"

env:
  REGISTRY: pinoched
  VERSION: $(git rev-parse --short "$GITHUB_SHA")

jobs:
  build-result:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            pinoched/result
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push result image
        uses: docker/build-push-action@v4
        with:
          dockerfile: result/Dockerfile
          context: result
          platforms: linux/amd64
          push: true
          tags:
            - "${{ env.VERSION }}"
            - "latest"
          # tags: ${{ steps.meta.outputs.tags }}
          # labels: ${{ steps.meta.outputs.labels }}
